ALTER TABLE "HistoryLog" ADD COLUMN IF NOT EXISTS "actorName" TEXT NOT NULL DEFAULT 'System';
ALTER TABLE "HistoryLog" ADD COLUMN IF NOT EXISTS "actorEmail" TEXT;
ALTER TABLE "HistoryLog" ADD COLUMN IF NOT EXISTS "actorRole" TEXT;
ALTER TABLE "HistoryLog" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "HistoryLog" DROP CONSTRAINT IF EXISTS "HistoryLog_userId_fkey";
ALTER TABLE "HistoryLog" ADD CONSTRAINT "HistoryLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
